// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const header: string;
export const header_container: string;
export const header_container_content: string;
export const header_social_container: string;
export const header_action_container: string;
export const header_tab: string;