// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const link: string;
export const sidenavbg: string;
export const sidenav: string;
export const closebtn: string;
export const openbtn: string;
